# Generated by Django 3.1.4 on 2021-01-01 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios/imagen')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nacim', models.DateField()),
                ('num_celular', models.BigIntegerField(blank=True, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('sentecia', models.DurationField(blank=True, null=True)),
                ('nick', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
