# Generated by Django 3.1.4 on 2021-01-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('contenido', models.CharField(max_length=250)),
                ('is_edit', models.BooleanField(blank=True, null=True)),
                ('reportaro', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='foros_descrp',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=70)),
                ('resumen', models.TextField(max_length=500)),
                ('contenido', models.TextField()),
                ('consola', models.CharField(max_length=20)),
                ('id_foro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('solicitud_moderacion', models.SmallIntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='foros/images')),
            ],
        ),
        migrations.CreateModel(
            name='videojuegos',
            fields=[
                ('genero', models.CharField(max_length=50)),
                ('consola', models.CharField(max_length=50)),
                ('estudio', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('id_videojuego', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
