# Generated by Django 3.1.4 on 2021-01-07 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='videojuegos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('consola', models.CharField(max_length=50)),
                ('estudio', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='foros_descrp',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=70)),
                ('resumen', models.TextField(max_length=500)),
                ('contenido', models.TextField()),
                ('consola', models.CharField(max_length=20)),
                ('codigo_foro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('solicitud_moderacion', models.SmallIntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='foros/images')),
                ('nick', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.videojuegos')),
            ],
        ),
    ]
