# Generated by Django 3.1.4 on 2021-02-14 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_editado', models.DateTimeField(auto_now=True)),
                ('contenido', models.CharField(max_length=250)),
                ('is_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='foros_descrp',
            fields=[
                ('id_foro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=70)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='foros/images')),
                ('contenido', models.TextField()),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='videojuegos',
            fields=[
                ('id_videojuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('consola', models.CharField(max_length=50)),
                ('estudio', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id_like', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foro.comentarios')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foro.foros_descrp')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foros_descrp',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foro.videojuegos'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='foro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.foros_descrp'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
