# Generated by Django 3.1.6 on 2021-02-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foros_descrp',
            options={'ordering': ['-fecha_creacion']},
        ),
    ]
